// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB44iEts3oaKsgDwL-KfcpCPLDKFUHpInY',
    appId: '1:576256441796:web:d855808e7d2b057ac07891',
    messagingSenderId: '576256441796',
    projectId: 'duolingo-a5101',
    authDomain: 'duolingo-a5101.firebaseapp.com',
    storageBucket: 'duolingo-a5101.firebasestorage.app',
    measurementId: 'G-8TDFD4YDPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC08oce3IvhtFDSW70shO69KJJz8vDvEWc',
    appId: '1:576256441796:android:48e9e71470f43fe3c07891',
    messagingSenderId: '576256441796',
    projectId: 'duolingo-a5101',
    storageBucket: 'duolingo-a5101.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB44iEts3oaKsgDwL-KfcpCPLDKFUHpInY',
    appId: '1:576256441796:web:e002099ad58d9396c07891',
    messagingSenderId: '576256441796',
    projectId: 'duolingo-a5101',
    authDomain: 'duolingo-a5101.firebaseapp.com',
    storageBucket: 'duolingo-a5101.firebasestorage.app',
    measurementId: 'G-K00LZ3DB5P',
  );
}
